AIS/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings 
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('dalilalaemal.urls')),
    path('basicinfo/',include('basicinfo.urls')),
    path('profiles/',include('profiles.urls')),
    path('accounts/',include('accounts.urls')),
    path('sales/',include('sales.urls')),
    path('products/',include('products.urls')),
    path('orders/',include('orders.urls')),
    path('employees/',include('employees.urls')),
    path('companys/',include('companys.urls')),
    path('pages/',include('pages.urls')),
    path('purchases/',include('purchases.urls')),
    path('inventorys/',include('inventorys.urls')),
    path('cashreceipt/',include('cashreceipt.urls')),
    
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ais/urls.py
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
"""ais URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/',include('pages.urls')),
    path('',include('dalilalaemal.urls')),
    path('basicinfo/',include('basicinfo.urls')),
    path('profiles/',include('profiles.urls')),
    path('companys/',include('companys.urls')),
    path('employees/',include('employees.urls')),
    path('products/',include('products.urls')),
    path('inventorys/',include('inventorys.urls')),
    path('sales/',include('sales.urls')),
    path('purchases/',include('purchases.urls')),

    # رابط طلب إعادة تعيين كلمة المرور
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    # رابط لإعلام المستخدم بأن بريد الاستعادة قد أُرسل
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    
    # رابط إعادة تعيين كلمة المرور باستخدام الرابط المرسل عبر البريد
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    # رابط لإعلام المستخدم بأن كلمة المرور قد تم تغييرها بنجاح
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basicinfo/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.basicinfo, name='basicinfo'),
    path('ajax/load-regions/', views.load_region, name='load_region'),
    path('ajax/load-states/', views.load_state, name='load_state'),
    path('ajax/load-citys/', views.load_city, name='load_city'),
    path('ajax/load_workSpecialtys/', views.load_workSpecialty, name='load_workSpecialty'),
    path('ajax/load_branchBanks/', views.load_branchBank, name='load_branchBank'),
    path('ajax/load_businessScopeSpecializations/', views.load_businessScopeSpecialization, name='load_businessScopeSpecialization')
]

basicinfo/forms.py
from django import forms
from .models import Persons, LegalPersons, BasicInfo, Countries, Region, States, Cities, BusinessScope
from companys.models import Company
from sales.models import Customers, Inventory
from purchases.models import Suppliers
from products.models import Items, ItemGrop
from django_select2.forms import Select2Widget
from inventorys.models import Inventory

class SetComboBox(forms.Form):
    sequence = forms.CharField(
        required=False,
        label='رقم القيد',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'رقم القيد'})
    )

    inventoryID = forms.ModelChoiceField(
        queryset=Inventory.objects.all(),
        label='المخزن',
        empty_label="اختر المخزن",
        required=False,
        widget=forms.Select(attrs={'name':'search_currencyID', 'class':'form-control', 'placeholder':'المخزن'})
    )
    
    currencyID = forms.ModelChoiceField(
        queryset=Countries.objects.all(),
        label='العملة',
        empty_label="اختر العملة",
        required=False,
        widget=forms.Select(attrs={'name':'search_currencyID', 'class':'form-control', 'placeholder':'العملة'})
    )

    companyID = forms.ModelChoiceField(
        queryset=Company.objects.all(),
        label='الشركة',
        empty_label="اختر الشركة",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'الشركة'})
    )

    customerID = forms.ModelChoiceField(
        queryset=Customers.objects.all(),
        label='العميل',
        empty_label="اختر العميل",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'العميل'})
    )

    itemID = forms.ModelChoiceField(
        queryset=Items.objects.all(),
        label='الصنف',
        empty_label="اختر الصنف",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'الصنف'})
    )
   
    itemGropID = forms.ModelChoiceField(
        queryset=ItemGrop.objects.all(),
        label='المجموعة',
        empty_label="اختر المجموعة",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'المجموعة'})
    )
   
    supplierID = forms.ModelChoiceField(
        queryset=Suppliers.objects.all(),
        label='المورد',
        empty_label="اختر المورد",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'المورد'})
    )

    businessScopeID = forms.ModelChoiceField(
        queryset=BusinessScope.objects.all(),
        label='مجال العمل',
        empty_label="اختر مجال العمل",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'مجال العمل'})
    )

    regionID = forms.ModelChoiceField(
        queryset=Region.objects.all(),
        label='المنق',
        empty_label="اختر المنطقة ",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'المنطقة'})
    )

    stateID = forms.ModelChoiceField(
        queryset=States.objects.all(),
        label='الولاية',
        empty_label="اختر الولاية ",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'الولاية'})
    )

    cityID = forms.ModelChoiceField(
        queryset=Cities.objects.all(),
        label='المدينة',
        empty_label="اختر المدينة ",
        required=False,
        widget=Select2Widget(attrs={'class':'form-control', 'placeholder':'المدينة'})
    )

    def __init__(self, *args, **kwargs):
        company_id = kwargs.pop('companyID', None)  # احصل على companyID من kwargs
        super(SetComboBox, self).__init__(*args, **kwargs)
        # تخصيص تسمية حقل currencyID
        self.fields['currencyID'].label_from_instance = lambda obj: obj.currency_ar
        if company_id:
            # تخصيص queryset بناءً على companyID
            self.fields['currencyID'].queryset = Countries.objects.filter(companyID=company_id)
            self.fields['inventoryID'].queryset = Inventory.objects.filter(companyID=company_id)
            self.fields['customerID'].queryset = Customers.objects.filter(companyID=company_id)
            self.fields['supplierID'].queryset = Suppliers.objects.filter(companyID=company_id)
            self.fields['itemID'].queryset = Items.objects.filter(companyID=company_id)
            self.fields['itemGrop'].queryset = ItemGrop.objects.filter(companyID=company_id)

class BasicInfoForm(forms.ModelForm):
    class Meta:
        model = BasicInfo
        fields = '__all__'
        widgets = {
            'nationalityID': forms.Select(attrs={'class':'form-control', 'placeholder':'الجنسية'}),
            'countryID': forms.Select(attrs={'class':'form-control', 'placeholder':'الدولة'}),
            'regionID': forms.Select(attrs={'class':'form-control', 'placeholder':'المنطقة'}),
            'stateID': forms.Select(attrs={'class':'form-control', 'data-placeholder': 'اختر الولاية'}),
            'cityID': forms.Select(attrs={'class':'form-control', 'placeholder':'المدينة'}),
            'address': forms.TextInput(attrs={'class':'form-control', 'placeholder':'وصف العنوان '}),
            'google_maps_location': forms.URLInput(attrs={'class':'form-control', 'placeholder':'العوان على خرائط قوقل'}),
            'latitude': forms.TextInput(attrs={'class':'form-control', 'type':'number', 'placeholder':'خط العرض latitude'}),
            'longitude': forms.TextInput(attrs={'class':'form-control', 'type':'number', 'placeholder':'خط الطول longitude'}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رقم الهاتف'}),
            'phoneOther': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رقم هاتف آخر'}),
            'email': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'إيميل'}),
            'website': forms.EmailInput(attrs={'class':'form-control', 'placeholder':'الموقع الإلكتروني'}),
            'fax': forms.TextInput(attrs={'class':'form-control', 'placeholder':'فاكس'}),
            'POBox': forms.TextInput(attrs={'class':'form-control', 'placeholder':'صندوق بريد'}),
            'bankID': forms.Select(attrs={'class':'form-control', 'placeholder':'البنك'}),
            'branchBankID': forms.Select(attrs={'class':'form-control', 'placeholder':'الفرع'}),
            'typeAccBankID': forms.Select(attrs={'class':'form-control', 'placeholder':'نوع الحساب'}),
            'accountNumber': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رقم الحساب'}),
            'IBANNumber': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رقم الآيبان'}),
            'ownerAccount': forms.TextInput(attrs={'class':'form-control', 'placeholder':'صاحب الحساب'}),
            'attachments': forms.ClearableFileInput(attrs={'class':'form-control', 'placeholder':'مرفقات'}),
            'photo': forms.ClearableFileInput(attrs={'class':'form-control', 'placeholder':'صورة / لوقو'}),
            'notes': forms.TextInput(attrs={'class':'form-control', 'placeholder':'ملاحظات'}),
            'documentLink': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رابط المستندات'}),
            'active': forms.CheckboxInput(attrs={'class':'form-control', 'placeholder':'نشط'}),
        }

class PersonForm(forms.ModelForm):
    class Meta:
        model = Persons
        fields = '__all__'
        widgets = {
            'basicInfoID': forms.Select(attrs={'class':'form-control', 'placeholder':'المعلومات الأساسية'}),
            'f_Name_ar': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الأول'}),
            's_Name_ar': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الثاني'}),
            't_Name_ar': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الثالث'}),
            'fo_Name_ar': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الرابع'}),
            'f_Name_en': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الأول'}),
            's_Name_en': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الثاني'}),
            't_Name_en': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الثالث'}),
            'fo_Name_en': forms.TextInput(attrs={'class':'form-control', 'placeholder':'الإسم الرابع'}),
            'dateOfBirth': forms.TextInput(attrs={'class':'form-control', 'type':'date', 'placeholder':'تاريخ الميلاد'}),
            'genderID': forms.Select(attrs={'class':'form-control', 'placeholder':'الجنس', 'value':'الجنس'}),
            'socialStatusID': forms.Select(attrs={'class':'form-control', 'placeholder':'الحالة الإجتماعية'}),
            'typeID': forms.Select(attrs={'class':'form-control', 'placeholder':'نوع الهوية'}),
            'id_number': forms.TextInput(attrs={'class':'form-control', 'placeholder':'رقم الهوية'}),
            'id_ExpiredDate': forms.TextInput(attrs={'class':'form-control','type':'date', 'placeholder':'تاريخ إنتهاء الهوية'}),
            'workTradeID': forms.Select(attrs={'class':'form-control', 'placeholder':'المهنة'}),
            'workSpecialtyID': forms.Select(attrs={'class':'form-control', 'placeholder':'التخصص'}),
            'skillsID': forms.SelectMultiple(attrs={'class':'form-control', 'placeholder':'المهارات'}),
            'languagesID': forms.SelectMultiple(attrs={'class':'form-control', 'placeholder':'اللغات'}),
            'jobTitleID': forms.Select(attrs={'class':'form-control', 'placeholder':'المسمى الوظيفي'}),
        }

class LegalPersonsForm (forms.ModelForm):
  class Meta:
      model = LegalPersons
      fields = '__all__'
      widgets = {
        'basicInfoID': forms.Select(attrs={'class':'form-control', 'placeholder':'المعلومات الأساسية'}),
        'businessScopeID': forms.Select(attrs={'class':'form-control', 'placeholder':'مجال العمل'}),
        'businessScopeSpecializationID': forms.Select(attrs={'class':'form-control', 'placeholder':'تخصص مجال العمل'}),

basicinfo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from basicinfo.models import *
from django.http import JsonResponse
from basicinfo.models import Region, States, Cities, WorkSpecialty, BranchBank, BusinessScope

# Create your views here.

def basicinfo(request):
    return render(request , 'basicinfo/basicinfo.html')

def load_region(request):
    country_id = request.GET.get('countryID')
    regions = Region.objects.filter(countryID_id=country_id).order_by('name_ar')
    return JsonResponse(list(regions.values('id', 'name_ar')), safe=False)

def load_state(request):
    regionID_id = request.GET.get('regionID')
    states = States.objects.filter(regionID_id=regionID_id).order_by('name_ar')
    return JsonResponse(list(states.values('id', 'name_ar')), safe=False)

def load_city(request):
    stateID_id = request.GET.get('stateID')
    cities = Cities.objects.filter(stateID_id=stateID_id).order_by('name_ar')
    return JsonResponse(list(cities.values('id', 'name_ar')), safe=False)

def load_workSpecialty(request):
    workTradeID_id = request.GET.get('workTradeID')
    workSpecialty = WorkSpecialty.objects.filter(workTradeID_id=workTradeID_id).order_by('name_ar')
    return JsonResponse(list(workSpecialty.values('id', 'name_ar')), safe=False)

def load_branchBank(request):
    bankID_id = request.GET.get('bankID')
    branchBank = BranchBank.objects.filter(bankID_id=bankID_id).order_by('name_ar')
    return JsonResponse(list(branchBank.values('id', 'name_ar')), safe=False)

def load_businessScopeSpecialization(request):
    businessScopeID_id = request.GET.get('businessScopeID')
    businessScopeSpecialization = BusinessScopeSpecialization.objects.filter(businessScopeID_id=businessScopeID_id).order_by('name_ar')
    return JsonResponse(list(businessScopeSpecialization.values('id', 'name_ar')), safe=False)

templates/basicinfo/basicinfo.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | Basic Info {% endblock %}
{% block content %}
<div class=" content-wrapper">
  <div class="main-title">
    <h4 class="form-group col-md-9">المعلومات الأساسية</h4>
  </div>
  <form method="GET" class="form-inline my-2 my-lg-0">  
    <button type="button" class="btn btn-main" data-toggle="modal" data-target="#staticBackdrop">إضافة حساب جديد</button>
    <button class="btn btn-main" type="submit">
      بحث 
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
    <a href="" class="btn btn-main" type="submit">
      إعادة تعيين
      <i class="fa-solid fa-rotate-right"></i>
    </a>
    <input class="form-control mr-sm-2 remove-outline"name="search_emp"  placeholder="بحث بالإسم" >
    <input class="form-control mr-sm-2 remove-outline"name="search_iqama" placeholder="بحث برقم الحدود" >
    <input class="form-control mr-sm-2 remove-outline"name="search_border" placeholder="بحث برقم الإقامة" >
    <input class="form-control mr-sm-2 remove-outline"name="search_company" placeholder="تصفية بالشركة" >
    <!-- <div class="form-control mr-sm-2 remove-outline"name="search_company">{{emp_form.companyID}}</div> -->

  </form>

  <div class="content">
    <!-- Start Search -->
    <!-- <p class="sub-title">إجمالي حسابات المستوى الأول : {{emp_count.count}}</p>
    <p class="sub-title">إجمالي حسابات المستوى الثاني : {{emp_count.count}}</p>
    <p class="sub-title">إجمالي حسابات المستوى الثالث : {{emp_count.count}}</p>
    <p class="sub-title">إجمالي حسابات المستوى الرابع : {{emp_count.count}}</p> -->
    <!-- End Search -->
    <br><br>
    <!-- Start Modal -->
    <div class="modal fade " id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-body">   
            <!-- Start Modal Countries -->
            {% include 'partials/_alerts.html' %}        
            <form method="POST">
              <div class="form-row main-title">
                <h5 class=" form-group col-md-9" id="staticBackdropLabel">إضافة حساب جديد</h5>
                <button type="submit" name="btnempsave" class="btn btn-save">إضافة</button>
                <button type="button" class="btn btn-close" data-dismiss="modal" aria-label="Close">
                  إلغاء
                </button>
              </div>
              <br>
              {% csrf_token %}
            
              <div class=" form-row"> 
                <h6 style="font-weight: bold;" class="col-md-3">إسم الحساب عربي</h6>
                <div class="form-group col-md-6"></div>
              </div>
              <div class=" form-row"> 
                <h6 style="font-weight: bold;" class="col-md-3">إسم الحساب إنجليزي</h6>
                <div class="form-group col-md-6"></div>
              </div>
              <div class=" form-row"> 
                <h6 style="font-weight: bold;" class="col-md-3">رمز الحساب </h6>
                <div class="form-group col-md-6"></div>
              </div>
              <div class=" form-row"> 
                <h6 style="font-weight: bold;" class="col-md-3">نوع الحساب </h6>
                <div class="form-group col-md-6"></div>
              </div>
              <div class=" form-row"> 
                <h6 style="font-weight: bold;" class="col-md-3">طبيعة الحساب </h6>
                <div class="form-group col-md-6"></div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- End Modal -->
    {% include 'partials/_alerts.html' %}
  <form method="POST">
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">رمز الحساب</th>
            <th scope="col">إسم الحساب</th>
            <th scope="col">الحساب الأب</th>
            <th scope="col">نوع الحساب</th>
            <th scope="col">العملة</th>
            <th scope="col">طبيعة الحساب</th>
            <th scope="col">توجيه الميزانية</th>
            <th scope="col">الوصف</th>
            <th scope="col">يمكن الدفع والتحصيل بهذا الحساب</th>
            <th scope="col">إجراءات</th>
          </tr>
        </thead>
        <tbody>
        <tr>
            <!-- لعمل ارقام تسلسلة -->
            <th scope="row">{{forloop.counter}}</th>
            <!-- تفاصيل الجدول -->
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
              <a class="btn-link" href="">
                <i class="fas fa-edit"></i>
              </a>
              <a href="" class="btn-link ">
                <i class="fa fa-print" aria-hidden="true"></i>
              </a>
              <a href="" class="btn-link ">
                <i class="fa fa-trash"></i>
              </a>
            </td>
            <td>
            </td>
        </tr>
        </tbody>
    </table>
  </form>
  </div>
</div>
{% endblock %}

templates/basicinfo/countries.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | Countries {% endblock %}
{% block content %}
<div class="container p-5 my-5 rounded border border-warning">
  <h1 class="text-center">معلومات الدول</h1>
  <br>
  <br>
  <!-- Start Modal Countries -->
  <form method="POST">
    {% csrf_token %}
    {% include 'partials/_alerts.html' %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCountryName_ar">إسم الدولة عربي</label>
        <input type="text" class="form-control" name="countryName_ar" id="inputCountryName_ar" required value="{{countryName_ar}}">
      </div>
      <div class="form-group col-md-4">
          <label for="inputCountryName_en">إسم الدولة إنجليزي</label>
          <input type="text" class="form-control" name="countryName_en" id="inputCountryName_en" required value="{{countryName_en}}">
        </div>
        <div class="form-group col-md-2">
          <label for="inputCode">رمز الدولة</label>
          <input type="text" class="form-control" name="code" id="inputCode" placeholder="" required value="{{code}}">
        </div>
      </div>
      <div class="form-group">
        <label for="inputCallKey">مفتاح الإتصال</label>
        <input type="text" class="form-control" name="callKey" id="inputCallKey" placeholder="" required value="{{callKey}}">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputNationality">الجنسية</label>
          <input type="text" class="form-control" name="nationality" id="inputNationality" placeholder="" required value="{{nationality}}">
        </div>
      </div>
      <button type="submit" name="btnsave" class="btn btn-warning">إضافة</button>
      <a href="{% url 'index' %}" class="btn btn-secondary">الرئيسية</a>
  </form>       
  <hr>  
  <h5>All Countries</h5> 
  <table class="table table-hover">
      <thead>
          <tr>
          <th scope="col">#</th>
          <th scope="col">إسم الدولة عربي</th>
          <th scope="col">إسم الدولة إنجليزي</th>
          <th scope="col">رمز الدولة</th>
          <th scope="col">مفتاح الإتصال</th>
          <th scope="col">تسمية الجنسية</th>
          <th scope="col">تعديل</th>
          <th scope="col">حذف</th>
          </tr>
      </thead>
      <tbody>
      {% for countrie in all_countrie %}
      <tr>
          <!-- لعمل ارقام تسلسلة -->
          <th scope="row">{{forloop.counter}}</th>
          <!-- تفاصيل الجدول -->
          <td>{{countrie.countryName_ar}}</td>
          <td>{{countrie.countryName_en}}</td>
          <td>{{countrie.code}}</td>
          <td>{{countrie.callKey}}</td>
          <td>{{countrie.nationality}}</td>
          <td>
            <a href="{% url 'edit_countrie' countrie_id=countrie.id %}" class="btn btn-info btn-sm" name="btnmodel" data-target="#edit_gender" data-toggle="modal">تعديل</a>
          </td>
          <td>
            <a href="{% url 'delete_countrie' countrie.id%}" class="btn btn-danger btn-sm">حذف</a>
          </td>

      </tr>
      {% endfor %}
      </tbody>
  </table>
  <div class="modal fade " id="countries" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">  
      <div class="modal-dialog modal-dialog-centered">   
      <div class="modal-content">
          <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">الدول</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          </div>
          <div class="modal-body">

          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal" id="btnclose">Close</button>
          <button onclick="addtocart()" class="btn btn-warning" >Confirm</button>
          <a href="{% url 'cart' %}" id="toCart" class="btn btn-warning" >To Cart</a>
          </div>
      </div>
      </div>
  </div>
  <!-- End Modal Countries -->
 <script>
    function addtocart(){
      document.getElementById('toCart').click();
      document.getElementById('btnclose').click();
      document.getElementById('frmaddtocart').submit();
    }
  </script>
</div>
{% endblock content %}

templates/basicinfo/sponser.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Gender {% endblock %}

{% block content %}
<div class="my-form container p-5 my-5 rounded border border-warning">

  <h1 class="text-center">معلومات الكفيل</h1>
  <br>
  <br>
    <form method="POST" action="add_sponser">
      {% csrf_token %}
      {% include 'partials/_alerts.html' %}
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputsponsName">إسم الكفيل</label>
          <input type="text" class="form-control" name="sponsName" id="inputsponsName" required value="{{sponsName}}">
        </div>
        <div class="form-group col-md-6">
          <ul >
            <label for="id_companyID">اختر الشركة :</label>
            <select name="companyID" class="form-control" id="id_companyID" fdprocessedid="osm1uo">
              <option>----- اختر الشركة -----</option>
              {% for company in all_company %}
                <option value="{{company.id}}">{{company.compName_ar}}</option>
              {% endfor %}
            </select>
          </ul>
        </div>
        <div class="form-group col-md-6">
          <button type="submit" class="btn btn-warning">إضافة</button>
          <a href="{% url 'generalsettings' %}" class="btn btn-secondary">الرئيسية</a>
        </div>
      </div>
    </form>
    <!-- <a href="{% url 'generalsettings' %}" class="btn btn-secondary">الرئيسية</a> -->

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">الكفيل</th>
                <th scope="col">الشركة</th>
                <th scope="col">تعديل</th>
                <th scope="col">حذف</th>
            </tr>
        </thead>
       
        <tbody>
        {% for sponser in all_sponser %}
        <tr>
            <!-- لعمل ارقام تسلسلة -->
            <th scope="row">{{forloop.counter}}</th>
            <!-- تفاصيل الجدول -->
            <td>{{sponser.sponsName}}</td>
            <td>{{sponser.companyID}}</td>
            <td>
              <a href="{% url 'sponser' %}" name="editgender" class="btn btn-info btn-sm">تعديل</a>
            </td>
            <td>

                <a href="{% url 'sponser' %}" class="btn btn-danger btn-sm">حذف</a>
            </td>
          
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}